// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatroom.proto

module chatroom.chatroom;

import google.protobuf;

enum protocVersion = 3006001;

class Login
{
    @Proto(1) string name = protoDefaultValue!string;
}

class Msg
{
    @Proto(1) string name = protoDefaultValue!string;
    @Proto(2) string message = protoDefaultValue!string;
}

class LoginReply
{
    @Proto(1) LoginState status = protoDefaultValue!LoginState;
    @Proto(2) string name = protoDefaultValue!string;

    enum LoginState
    {
        OK = 0,
        FAIL = 1,
    }
}
